### ISSUE TITLE
test getNodeInfoDetails does not compile

### ISSUE THREAD

**Issue by diederikd** [Strumenta/MPSServer#1]
The test getNodeInfoDetails does not compile in test case ServerDataExposerTest because of this line:

assert new ServerDataExposer.ModelInfo("jetbrains.mps.baseLanguage.structure", UUID.fromString("00000000-0000-4000-0000-011c895902ca"), null) equals integerConstant.refs["extends"].model;

In which modelInfo has wrong number of parameters

**Comment by ftomassetti** [comment]
Thank you, it should be fixed now
