### ISSUE TITLE
Plugin [id: 'com.strumenta.mpsserver', version: '0.1.0-snapshot'] was not found

### ISSUE THREAD

**Issue by kuruhuru** [Strumenta/MPSServer#15]
Hello!
I tryed to start MPSServer with buildscript from example. But Build failed with an exception.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/kuruhuru/dev/d0sl/sdk/d0SDK1/server.gradle' line: 9

* What went wrong:
Plugin [id: 'com.strumenta.mpsserver', version: '0.1.0-snapshot'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.strumenta.mpsserver:com.strumenta.mpsserver.gradle.plugin:0.1.0-snapshot')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by ftomassetti** [comment]
Hi, thank you for trying this out and sorry for the issue. It seems that the version of referred to is unreleased. Can you try changing the version from "0.1.0-snapshot" to "0.1.0" ?

**Comment by kuruhuru** [comment]
It works with 0.1.0 Thank you!

**Comment by ftomassetti** [comment]
Thank you! I corrected the Readme to reflect that
