### ISSUE TITLE
Avoid "mpsserver.home" not defined: put JARs under the deps solution folder

### ISSUE THREAD

**Issue by sergej-koscejev** [Strumenta/MPSServer#18]
Currently MPSServer dependencies are downloaded to mpscode/build/libs but then the full path to them is stored in the `deps.msd` as `$mpsserver.home/build/libs/some.jar`. The users of MPSServer won't have any such directory structure on their machines, the jar is packaged with the plugin itself.

To fix this, put the jars under the deps solution folder.

**Comment by ftomassetti** [comment]
Done
