### ISSUE TITLE
Resolve smart references when computing alternatives

### ISSUE THREAD

**Issue by alessiostalla** [Strumenta/MPSServer#33]

**Comment by ftomassetti** [comment]
hi @alessiostalla I looked into your change and it is not clear to me why NodeInfo needed to be changed. Could we look into this together when you are back?

**Comment by alessiostalla** [comment]
@ftomassetti sure, I added the concept alias field because concepts can have aliases and that's what MPS shows in the editor when you choose a type, if I'm not mistaken.
